replicaCount: 2

image:
  repository: 107721656410.dkr.ecr.us-east-1.amazonaws.com/ecommerce-platform-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 3000
